# Generated by Django 4.2.30 on 2026-09-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('purchase.completed', 'Purchase completed'), ('payment.failed', 'Payment failed'), ('renewal.completed', 'Renewal completed'), ('subscription.activated', 'Subscription activated'), ('subscription.canceled', 'Subscription canceled'), ('subscription.expired', 'Subscription expired'), ('trial.started', 'Trial started')], max_length=50)),
                ('dedupe_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('object_ref', models.CharField(blank=True, default='', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='events_even_event_t_38abd3_idx')],
            },
        ),
    ]
