# Generated by Django 4.2.30 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_welcome_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("purchase.completed", "Purchase completed"),
                    ("payment.failed", "Payment failed"),
                    ("payment.refunded", "Payment refunded"),
                    ("payment.disputed", "Payment disputed"),
                    ("payment.chargeback", "Payment charged back"),
                    ("payment.dispute_won", "Payment dispute won"),
                    ("renewal.completed", "Renewal completed"),
                    ("subscription.activated", "Subscription activated"),
                    ("subscription.canceled", "Subscription canceled"),
                    ("subscription.expired", "Subscription expired"),
                    ("trial.started", "Trial started"),
                ],
                max_length=50,
            ),
        ),
    ]
