# Generated by Django 4.2 on 2024-01-01 00:00
# This is a placeholder migration for the accounts app
# The User model already exists from Phase 1

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # No operations - User model already exists
    ]
