# Generated by Django - Merged migration for Discord fields and user managers

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        # This merges both branches:
        # - 0002_alter_user_managers_alter_user_last_login (Phase 1)
        # - 0002_add_discord_fields (Discord)
    ]

    operations = [
        # Discord fields
        migrations.AddField(
            model_name='user',
            name='discord_id',
            field=models.CharField(max_length=255, blank=True, null=True, unique=True, help_text='Discord user ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(max_length=255, blank=True, help_text='Discord username'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_avatar',
            field=models.CharField(max_length=255, blank=True, help_text='Discord avatar hash'),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_verified',
            field=models.BooleanField(default=False, help_text='Whether Discord has been verified via OAuth'),
        ),
    ]
