# Generated by Django 5.0.14 on 2026-03-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_add_discord_fields"),
        ("accounts", "0002_alter_user_managers_alter_user_last_login"),
    ]

    operations = []
