# Generated by Django - Add DiscordAppConfig model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_discord_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Community Platform', max_length=100)),
                ('client_id', models.CharField(help_text='Discord Application Client ID', max_length=255)),
                ('client_secret', models.CharField(help_text='Discord Application Client Secret', max_length=255)),
                ('redirect_uri', models.URLField(default='http://localhost:8000/auth/discord/callback/', help_text='Must match Discord app settings')),
                ('is_active', models.BooleanField(default=True, help_text='Enable Discord login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord App Configuration',
                'verbose_name_plural': 'Discord App Configuration',
            },
        ),
    ]
