# Generated by Django 5.0.14 on 2026-03-16 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_discord_fields"),
        ("accounts", "0003_merge_20260316_2041"),
    ]

    operations = []
