# Generated by Django 5.0.14 on 2026-03-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_merge_20260316_2048"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="discord_avatar",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_username",
        ),
        migrations.RemoveField(
            model_name="user",
            name="discord_verified",
        ),
    ]
