# Generated by Django 5.0.14 on 2026-03-16 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_discordappconfig"),
        ("accounts", "0005_remove_user_discord_avatar_remove_user_discord_id_and_more"),
    ]

    operations = []
