# Generated by Django 5.0.14 on 2026-03-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_merge_20260316_2243"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discord_avatar",
            field=models.CharField(blank=True, help_text="Discord avatar hash", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_id",
            field=models.CharField(
                blank=True, help_text="Discord user ID", max_length=255, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_username",
            field=models.CharField(blank=True, help_text="Discord username", max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="discord_verified",
            field=models.BooleanField(
                default=False, help_text="Whether Discord has been verified via OAuth"
            ),
        ),
    ]
