# Generated by Django 5.2 on 2026-03-28 02:55
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add nickname field to User model for custom display names."""

    dependencies = [
        ('accounts', '0007_user_discord_avatar_user_discord_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(
                blank=True,
                help_text='Custom display name shown in gift emails. Falls back to first name if empty.',
                max_length=50,
                null=True,
                verbose_name='Display Name',
            ),
        ),
    ]
