# Generated by Django 5.0.14 on 2026-03-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="api_apirequ_api_key_c39608_idx",
            old_name="api_apirequestlog_api_key_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="api_apirequ_user_id_873b9d_idx",
            old_name="api_apirequestlog_user_created_at_idx",
        ),
        migrations.RenameIndex(
            model_name="apirequestlog",
            new_name="api_apirequ_endpoin_b7e184_idx",
            old_name="api_apirequestlog_endpoint_created_at_idx",
        ),
    ]
