# Generated by Django 4.2.30 on 2026-09-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_welcome_periodic_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="periodicjob",
            name="state",
            field=models.JSONField(
                blank=True, default=dict, help_text="Scheduler sweep cursor (dict)."
            ),
        ),
    ]
