# Generated by Django 5.2.12 on 2026-04-04 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("telegram_bot_token", models.CharField(blank=True, max_length=255)),
                ("telegram_bot_username", models.CharField(blank=True, max_length=255)),
                (
                    "telegram_webhook_url",
                    models.URLField(blank=True, help_text="Override auto webhook URL"),
                ),
                ("discord_bot_token", models.CharField(blank=True, max_length=255)),
                (
                    "discord_guild_id",
                    models.CharField(
                        blank=True, help_text="Discord server (guild) ID", max_length=64
                    ),
                ),
                ("discord_client_id", models.CharField(blank=True, max_length=255)),
                ("discord_client_secret", models.CharField(blank=True, max_length=255)),
                ("discord_redirect_uri", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bot Configuration",
                "verbose_name_plural": "Bot Configurations",
            },
        ),
        migrations.CreateModel(
            name="DiscordAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("discord_user_id", models.CharField(max_length=64, unique=True)),
                ("guild_id", models.CharField(blank=True, max_length=64)),
                ("username", models.CharField(blank=True, max_length=255)),
                (
                    "roles",
                    models.JSONField(blank=True, default=list, help_text="Cached list of role IDs"),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Discord Account",
                "verbose_name_plural": "Discord Accounts",
            },
        ),
        migrations.CreateModel(
            name="TelegramAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Telegram numeric user ID (from message.from.id). Used for banning/unbanning.",
                        null=True,
                    ),
                ),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Account",
                "verbose_name_plural": "Telegram Accounts",
            },
        ),
        migrations.CreateModel(
            name="TelegramVerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_verification_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram Verification Token",
                "verbose_name_plural": "Telegram Verification Tokens",
            },
        ),
        migrations.CreateModel(
            name="BotAccessAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("grant", "Grant"),
                            ("revoke", "Revoke"),
                            ("link", "Link"),
                            ("unlink", "Unlink"),
                            ("sync", "Sync"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("discord", "Discord")], max_length=10
                    ),
                ),
                ("target", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")], max_length=10
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_audits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Access Audit",
                "verbose_name_plural": "Bot Access Audits",
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="bot_integra_user_id_4e1668_idx"
                    ),
                    models.Index(fields=["status"], name="bot_integra_status_ffee7a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="PlanChannelMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("discord", "Discord")], max_length=10
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="Telegram channel ID/username or Discord role ID", max_length=255
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="Human-readable name", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bot_channel_mappings",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Channel Mapping",
                "verbose_name_plural": "Plan Channel Mappings",
                "unique_together": {("plan", "platform", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="UserChannelAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("discord", "Discord")], max_length=10
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Channel Assignment",
                "verbose_name_plural": "User Channel Assignments",
                "unique_together": {("user", "platform", "external_id")},
            },
        ),
    ]
