# Generated by Django 4.2.30 on 2026-09-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botconfig',
            name='telegram_control_channel_id',
            field=models.CharField(blank=True, default='', help_text='Admin/control channel ID — rejected as a target channel', max_length=64),
        ),
    ]
