# Generated by Django 4.2.30 on 2026-09-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_integration", "0002_botconfig_telegram_control_channel_id"),
        ("bot_integration", "0002_botruntimestate"),
    ]

    operations = []
