# Generated by Django 4.2.30 on 2026-09-19 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_integration", "0003_merge_20260919_2223"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="botconfig",
            name="telegram_control_channel_id",
        ),
    ]
