# Generated by Django 4.2.30 on 2026-09-20 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('block_type', models.CharField(max_length=30)),
                ('schema', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='email_media/%Y/%m/')),
                ('public_url', models.URLField(help_text='HTTPS public URL to serve the asset.')),
                ('alt_text', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('transactional', 'Transactional'), ('marketing', 'Marketing')], default='marketing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VariableSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('preview_value', models.CharField(blank=True, default='', max_length=255)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('editor_mode', models.CharField(choices=[('visual', 'Visual builder'), ('html', 'Raw HTML')], max_length=10)),
                ('subject', models.CharField(max_length=255)),
                ('preview_text', models.CharField(blank=True, default='', max_length=255)),
                ('html', models.TextField(help_text='Canonical render source. Preserved verbatim for editor_mode=html.')),
                ('plain_text', models.TextField(blank=True, default='')),
                ('visual_blocks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='emailing.template')),
                ('variables', models.ManyToManyField(blank=True, related_name='template_versions', to='emailing.variablespec')),
            ],
            options={
                'ordering': ['template', '-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('to_email', models.EmailField(max_length=254)),
                ('kind', models.CharField(choices=[('transactional', 'Transactional'), ('marketing', 'Marketing')], default='marketing', max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('suppressed', 'Suppressed')], default='queued', max_length=20)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='emailing.templateversion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_deliveries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
