# Generated by Django 5.0.14 on 2026-03-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LandingPage",
        ),
    ]
