# Generated by Django 5.0.14 on 2026-03-18 16:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("pro", "Pro"),
                            ("enterprise", "Enterprise"),
                        ],
                        help_text="Plan tier level",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(help_text="Display name for the plan", max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Plan description shown to users"),
                ),
                (
                    "max_projects",
                    models.PositiveIntegerField(
                        default=0, help_text="Maximum number of projects allowed"
                    ),
                ),
                (
                    "max_storage_mb",
                    models.PositiveIntegerField(default=0, help_text="Maximum storage in MB"),
                ),
                (
                    "api_calls_per_day",
                    models.PositiveIntegerField(default=0, help_text="API call limit per day"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this plan is available for new subscriptions",
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order for display in plan lists"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "plan",
                "verbose_name_plural": "plans",
                "ordering": ["display_order", "tier"],
            },
        ),
        migrations.CreateModel(
            name="PlanPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                        help_text="Billing interval",
                        max_length=10,
                    ),
                ),
                (
                    "price_cents",
                    models.PositiveIntegerField(help_text="Price in cents (e.g., 999 for $9.99)"),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", help_text="ISO 4217 currency code", max_length=3
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this price is currently offered"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The plan this price applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan price",
                "verbose_name_plural": "plan prices",
                "ordering": ["plan", "interval"],
                "unique_together": {("plan", "interval", "currency")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="Current subscription status",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False, help_text="Whether this subscription grants current access"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, help_text="When the subscription started"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When the subscription expires/ended", null=True
                    ),
                ),
                (
                    "canceled_at",
                    models.DateTimeField(
                        blank=True, help_text="When the subscription was canceled", null=True
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider (e.g., stripe, paypal)",
                        max_length=50,
                    ),
                ),
                (
                    "provider_subscription_id",
                    models.CharField(
                        blank=True, help_text="Subscription ID in payment provider", max_length=255
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="The subscribed plan",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "plan_price",
                    models.ForeignKey(
                        blank=True,
                        help_text="The price/interval selected",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscriptions",
                        to="subscriptions.planprice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns this subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription",
                "verbose_name_plural": "subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("activated", "Activated"),
                            ("renewed", "Renewed"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                            ("upgraded", "Upgraded"),
                            ("downgraded", "Downgraded"),
                        ],
                        help_text="Type of subscription event",
                        max_length=20,
                    ),
                ),
                (
                    "previous_plan_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Previous plan ID (for upgrades/downgrades)",
                        null=True,
                    ),
                ),
                (
                    "new_plan_id",
                    models.UUIDField(
                        blank=True, help_text="New plan ID (for upgrades/downgrades)", null=True
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        blank=True, help_text="Previous subscription status", max_length=10
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, help_text="New subscription status", max_length=10
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, help_text="Additional event metadata"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Human-readable notes about this event"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        help_text="The subscription this event relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who owns the subscription",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription history",
                "verbose_name_plural": "subscription histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
