# Generated by Django 5.0.14 on 2026-03-18 17:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="upgrade_priority",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Higher number = better plan. Used for upgrade validation."
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who granted this subscription",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_subscriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="granted_reason",
            field=models.TextField(blank=True, help_text="Reason for admin grant"),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_admin_grant",
            field=models.BooleanField(
                default=False, help_text="Whether this subscription was granted by an admin"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="is_trial",
            field=models.BooleanField(
                default=False, help_text="Whether this is a trial subscription"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="prorated_credit_cents",
            field=models.PositiveIntegerField(
                default=0, help_text="Credit from previous subscription applied to this one (cents)"
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="trial_days",
            field=models.PositiveSmallIntegerField(default=0, help_text="Number of trial days"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("trial", "Trial"),
                ],
                default="pending",
                help_text="Current subscription status",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("activated", "Activated"),
                    ("renewed", "Renewed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("upgraded", "Upgraded"),
                    ("downgraded", "Downgraded"),
                    ("trial_started", "Trial Started"),
                    ("trial_expired", "Trial Expired"),
                    ("admin_granted", "Admin Granted"),
                    ("gift_redeemed", "Gift Redeemed"),
                ],
                help_text="Type of subscription event",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="new_plan_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="new_status",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="previous_plan_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="previous_status",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="GiftSubscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(help_text="Unique gift code", max_length=50, unique=True),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Duration of the gifted subscription"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email of intended recipient (optional)",
                        max_length=254,
                    ),
                ),
                ("message", models.TextField(blank=True, help_text="Personal message from sender")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="When this gift code expires", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subscription created from this gift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gift_source",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Plan being gifted",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="gift_subscriptions",
                        to="subscriptions.plan",
                    ),
                ),
                (
                    "redeemed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who redeemed this gift",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_gifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the gift",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_gifts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "gift subscription",
                "verbose_name_plural": "gift subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PlanDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Discount code (e.g., SUMMER20)", max_length=50, unique=True
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description of the discount", max_length=255
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        help_text="Type of discount",
                        max_length=20,
                    ),
                ),
                (
                    "discount_value",
                    models.PositiveIntegerField(help_text="Discount value (percentage or cents)"),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum number of times this discount can be used (null = unlimited)",
                        null=True,
                    ),
                ),
                (
                    "use_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times this discount has been used"
                    ),
                ),
                ("valid_from", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="When this discount expires (null = never)", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicable_plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Plans this discount applies to (empty = all plans)",
                        related_name="discounts",
                        to="subscriptions.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "plan discount",
                "verbose_name_plural": "plan discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="subscription",
            name="applied_discount",
            field=models.ForeignKey(
                blank=True,
                help_text="Discount applied to this subscription",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subscriptions",
                to="subscriptions.plandiscount",
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("subscription_created", "Subscription Created"),
                            ("subscription_upgraded", "Subscription Upgraded"),
                            ("trial_started", "Trial Started"),
                            ("trial_expired", "Trial Expired"),
                            ("admin_granted_plan", "Admin Granted Plan"),
                            ("subscription_canceled", "Subscription Canceled"),
                            ("subscription_expired", "Subscription Expired"),
                            ("gift_created", "Gift Created"),
                            ("gift_redeemed", "Gift Redeemed"),
                        ],
                        help_text="Type of event",
                        max_length=30,
                    ),
                ),
                ("data", models.JSONField(default=dict, help_text="Event payload data")),
                (
                    "processed",
                    models.BooleanField(
                        default=False, help_text="Whether this event has been processed"
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        help_text="Subscription this event relates to (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this event relates to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "subscription event",
                "verbose_name_plural": "subscription events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "processed"], name="subscriptio_event_t_779825_idx"
                    ),
                    models.Index(
                        fields=["user", "created_at"], name="subscriptio_user_id_317692_idx"
                    ),
                ],
            },
        ),
    ]
