# Generated by Django 5.2.12 on 2026-04-11 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_add_trial_support"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="usertrialusage",
            name="unique_user_trial_per_plan",
        ),
        migrations.AlterUniqueTogether(
            name="usertrialusage",
            unique_together={("user", "plan")},
        ),
    ]
