# Generated by Django 5.2.12 on 2026-04-12 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_remove_usertrialusage_unique_user_trial_per_plan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="tier",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("basic", "Basic"),
                    ("pro", "Pro"),
                    ("enterprise", "Enterprise"),
                ],
                help_text="Plan tier level",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={("tier", "is_trial")},
        ),
    ]
