# Generated by Django 5.2.12 on 2026-04-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_remove_tier_unique"),
        ("subscriptions", "0004_alter_plan_tier_alter_plan_unique_together"),
    ]

    operations = []
