# Generated by Django 5.2.12 on 2026-04-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_merge_20260412_2126"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="display_order",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Order for display in plan lists (higher = shown first)"
            ),
        ),
        migrations.AlterField(
            model_name="subscriptionhistory",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("activated", "Activated"),
                    ("renewed", "Renewed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("upgraded", "Upgraded"),
                    ("downgraded", "Downgraded"),
                    ("trial_started", "Trial Started"),
                    ("trial_expired", "Trial Expired"),
                    ("admin_granted", "Admin Granted"),
                    ("gift_received", "Gift Received"),
                ],
                help_text="Type of subscription event",
                max_length=20,
            ),
        ),
    ]
