# Generated by Django 5.2.12 on 2026-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0006_alter_plan_display_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geoplanprice",
            name="interval",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly")],
                help_text="Billing interval",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="planprice",
            name="interval",
            field=models.CharField(
                choices=[("monthly", "Monthly"), ("quarterly", "Quarterly"), ("yearly", "Yearly")],
                help_text="Billing interval",
                max_length=10,
            ),
        ),
    ]
