# Generated by Django 4.2.30 on 2026-09-19 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_alter_geoplanprice_interval_alter_planprice_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='geo_plan_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='subscriptions.geoplanprice', verbose_name='resolved geo price'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_cents',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
