# Generated by Django 4.2.30 on 2026-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_subscription_geo_plan_price_subscription_price_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='base_price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='subscription',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
