# Generated by Django 4.2.30 on 2026-09-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_base_price_cents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pre_expiry', 'Pre-expiry'), ('post_expiry', 'Post-expiry')], max_length=16)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_recipient', models.EmailField(blank=True, default='', max_length=254)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='subscriptions.subscription')),
            ],
            options={
                'verbose_name': 'subscription reminder',
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptionreminder',
            constraint=models.UniqueConstraint(fields=('subscription', 'kind'), name='uniq_reminder_per_kind'),
        ),
    ]
