# Generated by Django 4.2.30 on 2026-09-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0013_plan_description_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planfeature",
            name="plan",
            field=models.ForeignKey(
                help_text="The plan this feature bullet belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="subscriptions.plan",
            ),
        ),
        migrations.AlterField(
            model_name="planfeature",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Display order on the card (lower = shown first)"
            ),
        ),
        migrations.AlterField(
            model_name="planfeature",
            name="text",
            field=models.CharField(
                help_text="Feature bullet text shown on the pricing card", max_length=255
            ),
        ),
    ]
