# Generated by Django 4.2.30 on 2026-09-20 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0008_subscription_geo_plan_price_subscription_price_cents_and_more'),
        ('payments', '0006_paymentintent_applied_coupon_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent off'), ('fixed', 'Fixed amount off (cents)')], max_length=10)),
                ('percent_off', models.PositiveIntegerField(blank=True, help_text='0-100. Used when discount_type=percent.', null=True)),
                ('amount_off_cents', models.PositiveIntegerField(blank=True, help_text='Used when discount_type=fixed.', null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Null = unlimited.', null=True)),
                ('max_per_user', models.PositiveIntegerField(default=1)),
                ('plan_tiers', models.JSONField(blank=True, default=list, help_text='e.g. ["pro","enterprise"]. Empty = all tiers.')),
                ('stackable_with_referral', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promotions.coupon')),
                ('payment_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='payments.paymentintent')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to='subscriptions.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'payment_intent')},
            },
        ),
    ]
