# Generated by Django 4.2.30 on 2026-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponredemption',
            name='base_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='final_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponredemption',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
