# Generated by Django 4.2.30 on 2026-09-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('promotions', '0002_couponredemption_base_amount_cents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='campaigns.campaign'),
        ),
    ]
