# Generated by Django 5.2.12 on 2026-03-24 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymentintent",
            old_name="amount_cents",
            new_name="amount",
        ),
        migrations.AddField(
            model_name="paymentintent",
            name="plan_price",
            field=models.ForeignKey(
                blank=True,
                help_text="Price selected for the plan",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_intents",
                to="subscriptions.planprice",
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country code used for pricing", max_length=2
            ),
        ),
    ]
