# Generated by Django 5.2.12 on 2026-04-04 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0011_referral_discount_used_and_more"),
        ("payments", "0002_rename_amount_cents_paymentintent_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentintent",
            name="applied_referral_discount",
            field=models.ForeignKey(
                blank=True,
                help_text="Referral whose discount was applied to this payment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_intents",
                to="growth.referral",
            ),
        ),
    ]
