# Generated by Django 4.2.30 on 2026-09-20 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='applied_coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='coupon_discount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
