# Generated by Django 4.2.30 on 2026-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentintent_applied_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='base_amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
