# Generated by Django 4.2.30 on 2026-09-20 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emailing', '0001_initial'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('trigger_event_type', models.CharField(choices=[('purchase.completed', 'Purchase completed'), ('payment.failed', 'Payment failed'), ('renewal.completed', 'Renewal completed'), ('subscription.activated', 'Subscription activated'), ('subscription.canceled', 'Subscription canceled'), ('subscription.expired', 'Subscription expired'), ('trial.started', 'Trial started')], max_length=50)),
                ('delay_minutes', models.PositiveIntegerField(default=0, help_text='Wait this long after the event before firing.')),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automation_rules', to='emailing.templateversion')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('fired', 'Fired'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('scheduled_at', models.DateTimeField()),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automation_runs', to='emailing.delivery')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to='events.event')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='automation.automationrule')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='automation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='automation__status_218058_idx')],
                'unique_together': {('rule', 'event')},
            },
        ),
    ]
