# Generated by Django 4.2.30 on 2026-09-26 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_alter_planfeature_plan_alter_planfeature_position_and_more"),
        ("support", "0002_supportticket_withdrawn"),
    ]

    operations = [
        migrations.AlterField(
            model_name="affiliatelink",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional: hidden plan auto-assigned when an access request using this link is approved (you can still override)",
                limit_choices_to={"is_hidden": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="affiliate_links",
                to="subscriptions.plan",
            ),
        ),
    ]
