# Generated by Django 5.0.14 on 2026-03-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_auditlog_audit_audit_action_766c6d_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_auditlog_action_created_at_idx",
        ),
        migrations.RemoveIndex(
            model_name="auditlog",
            name="audit_auditlog_object_type_object_id_idx",
        ),
    ]
