# Generated by Django 4.2.30 on 2026-09-20 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupAttribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('utm_source', models.CharField(blank=True, default='', max_length=100)),
                ('utm_medium', models.CharField(blank=True, default='', max_length=100)),
                ('utm_campaign', models.CharField(blank=True, default='', max_length=100)),
                ('utm_term', models.CharField(blank=True, default='', max_length=100)),
                ('utm_content', models.CharField(blank=True, default='', max_length=100)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('referring_campaign', models.ForeignKey(blank=True, help_text='The G2 campaign whose link brought this user (if known).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_signups', to='campaigns.campaign')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signup_attribution', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
