# Generated by Django 4.2.30 on 2026-09-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("risk", "0002_bootstrap_groups"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="risksignal",
            new_name="risk_risksi_signal__7c438c_idx",
            old_name="risk_rs_type_ts",
        ),
    ]
