# Generated by Django for Growth Module

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    """
    Initial migration for growth app.

    Creates GiftInvite and PendingGiftClaim models.
    """

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(help_text='Email address of the intended recipient', max_length=254)),
                ('recipient_email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of email for lookup without exposing email', max_length=64)),
                ('claim_token', models.CharField(help_text='Secure token for claiming the gift', max_length=64, unique=True)),
                ('claim_token_hash', models.CharField(db_index=True, help_text='SHA-256 hash of the claim token', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent_at', models.DateTimeField(blank=True, help_text='When the gift email was sent', null=True)),
                ('email_resend_count', models.PositiveSmallIntegerField(default=0, help_text='Number of times the email has been resent')),
                ('last_email_sent_at', models.DateTimeField(blank=True, help_text='When the gift email was last sent/resent', null=True)),
                ('expires_at', models.DateTimeField(help_text='When this invite expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, help_text='User who claimed this gift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_invites_claimed', to=settings.AUTH_USER_MODEL)),
                ('gift_subscription', models.OneToOneField(help_text='The gift subscription this invite is for', on_delete=django.db.models.deletion.CASCADE, related_name='gift_invite', to='subscriptions.giftsubscription')),
            ],
            options={
                'verbose_name': 'gift invite',
                'verbose_name_plural': 'gift invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingGiftClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_token_hash', models.CharField(db_index=True, help_text='Hash of the claim token being claimed', max_length=64)),
                ('session_key', models.CharField(db_index=True, help_text='Django session key for correlation', max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the requester', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the requester')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, help_text='User who eventually claimed this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_claims_processed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'pending gift claim',
                'verbose_name_plural': 'pending gift claims',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftinvite',
            index=models.Index(fields=['recipient_email_hash', 'status'], name='growth_gift_recipie_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='giftinvite',
            index=models.Index(fields=['claim_token_hash'], name='growth_gift_claim_t_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='giftinvite',
            index=models.Index(fields=['status', 'expires_at'], name='growth_gift_status__123456_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinggiftclaim',
            index=models.Index(fields=['session_key', 'status'], name='growth_pend_session_123456_idx'),
        ),
        migrations.AddIndex(
            model_name='pendinggiftclaim',
            index=models.Index(fields=['claim_token_hash', 'status'], name='growth_pend_claim_t_123456_idx'),
        ),
    ]
