# Generated by Django 5.2.12 on 2026-03-27 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="giftinvite",
            new_name="growth_gift_recipie_1ec746_idx",
            old_name="growth_gift_recipie_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="giftinvite",
            new_name="growth_gift_claim_t_7ada7b_idx",
            old_name="growth_gift_claim_t_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="giftinvite",
            new_name="growth_gift_status_352735_idx",
            old_name="growth_gift_status__123456_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinggiftclaim",
            new_name="growth_pend_session_a42c9e_idx",
            old_name="growth_pend_session_123456_idx",
        ),
        migrations.RenameIndex(
            model_name="pendinggiftclaim",
            new_name="growth_pend_claim_t_b1a101_idx",
            old_name="growth_pend_claim_t_123456_idx",
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="claim_token",
            field=models.CharField(
                db_index=True,
                help_text="Secure token for claiming the gift",
                max_length=64,
                unique=True,
            ),
        ),
    ]
