# Generated by Django 5.2 on 2026-03-29 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("growth", "0002_referral_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("default_reward_percentage", models.DecimalField(decimal_places=2, default=20.0, help_text="Default percentage of referred purchase amount to reward referrer (e.g., 20.00 = 20%)", max_digits=5)),
                ("minimum_purchase_amount_cents", models.PositiveIntegerField(default=0, help_text="Minimum purchase amount (in cents) required to trigger a reward")),
                ("rewards_enabled", models.BooleanField(default=True, help_text="Enable or disable referral rewards system-wide")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "referral settings",
                "verbose_name_plural": "referral settings",
            },
        ),
        migrations.CreateModel(
            name="ReferralReward",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("amount_cents", models.PositiveIntegerField(help_text="Reward amount in cents")),
                ("currency", models.CharField(default="USD", help_text="Currency of the reward amount", max_length=3)),
                ("referred_purchase_amount_cents", models.PositiveIntegerField(help_text="Original purchase amount that triggered this reward (in cents)")),
                ("reward_percentage", models.DecimalField(decimal_places=2, help_text="Percentage used to calculate this reward", max_digits=5)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("credited", "Credited"), ("used", "Used"), ("expired", "Expired")], default="pending", max_length=10)),
                ("used_amount_cents", models.PositiveIntegerField(default=0, help_text="Amount already used/consumed (in cents)")),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("referral", models.OneToOneField(help_text="The referral that generated this reward", on_delete=django.db.models.deletion.CASCADE, related_name="reward", to="growth.referral")),
                ("referrer", models.ForeignKey(help_text="User who earned this reward", on_delete=django.db.models.deletion.CASCADE, related_name="referral_rewards", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "referral reward",
                "verbose_name_plural": "referral rewards",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReferralRewardLedger",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("transaction_type", models.CharField(choices=[("credit", "Credit"), ("debit", "Debit"), ("expired", "Expired"), ("reversal", "Reversal")], max_length=10)),
                ("amount_cents", models.IntegerField(help_text="Transaction amount in cents (positive for credit, negative for debit)")),
                ("balance_after_cents", models.IntegerField(help_text="Reward balance after this transaction (in cents)")),
                ("description", models.CharField(blank=True, help_text="Description of what this transaction represents", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(blank=True, default=dict, help_text="Additional metadata about this transaction")),
                ("reward", models.ForeignKey(help_text="The reward being transacted", on_delete=django.db.models.deletion.CASCADE, related_name="ledger_entries", to="growth.referralreward")),
                ("subscription", models.ForeignKey(blank=True, help_text="Subscription this reward was applied to (if applicable)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="referral_reward_entries", to="subscriptions.subscription")),
            ],
            options={
                "verbose_name": "referral reward ledger entry",
                "verbose_name_plural": "referral reward ledger entries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(fields=["referrer", "status"], name="growth_refer_referre_0a7f7e_idx"),
        ),
        migrations.AddIndex(
            model_name="referralreward",
            index=models.Index(fields=["status", "expires_at"], name="growth_refer_status__15b3b5_idx"),
        ),
    ]
