# Generated by Django 5.2.12 on 2026-03-28 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0002_referral_tracking"),
        (
            "growth",
            "0002_rename_growth_gift_recipie_123456_idx_growth_gift_recipie_1ec746_idx_and_more",
        ),
    ]

    operations = []
