# Generated by Django 5.2.12 on 2026-03-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0003_merge_20260328_1751"),
        ("growth", "0003_referral_rewards"),
    ]

    operations = []
