# Generated by Django 5.2.12 on 2026-03-28 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0004_merge_0003_merge_20260328_1751_0003_referral_rewards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="referralreward",
            new_name="growth_refe_referre_4e76ba_idx",
            old_name="growth_refer_referre_0a7f7e_idx",
        ),
        migrations.RenameIndex(
            model_name="referralreward",
            new_name="growth_refe_status_b5ec8e_idx",
            old_name="growth_refer_status__15b3b5_idx",
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="claim_token",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="claim_token_hash",
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="claimed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gift_invites_claimed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="email_resend_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="last_email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="giftinvite",
            name="recipient_email_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="claim_token_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="error_message",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pending_claims_processed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="session_key",
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="pendinggiftclaim",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="referralrewardledger",
            name="description",
            field=models.CharField(
                blank=True, help_text="Description of transaction", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="referralrewardledger",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, help_text="Additional metadata"),
        ),
        migrations.AlterField(
            model_name="referralsettings",
            name="default_reward_percentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("20.00"),
                help_text="Default percentage of referred purchase amount to reward referrer (e.g., 20.00 = 20%)",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
    ]
