# Generated by Django 5.2.12 on 2026-03-29 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0002_viral_referral_fields"),
        (
            "growth",
            "0005_rename_growth_refer_referre_0a7f7e_idx_growth_refe_referre_4e76ba_idx_and_more",
        ),
    ]

    operations = []
