# Generated by Django 5.2.12 on 2026-03-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0006_merge_20260330_0009"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="referralreward",
            name="growth_refe_status_b5ec8e_idx",
        ),
        migrations.RenameIndex(
            model_name="referralreward",
            new_name="growth_refe_status_5d830e_idx",
            old_name="growth_refer_unlock_idx",
        ),
        migrations.RemoveField(
            model_name="referralreward",
            name="expires_at",
        ),
    ]
