# Generated by Django 5.2.12 on 2026-04-03 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0002_referral_safety_fields"),
        ("growth", "0007_remove_referralreward_growth_refe_status_b5ec8e_idx_and_more"),
    ]

    operations = []
