# Generated by Django 5.2.12 on 2026-04-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0008_merge_20260403_2031"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="referral",
            name="growth_refer_fraud_check_idx",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="discount_used",
        ),
        migrations.RemoveField(
            model_name="referral",
            name="reward_created",
        ),
    ]
