# Generated by Django 5.2.12 on 2026-04-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("growth", "0010_referee_benefit_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="discount_used",
            field=models.BooleanField(
                default=False,
                help_text="Whether the referee has used their one-time checkout discount",
            ),
        ),
        migrations.AddField(
            model_name="referralsettings",
            name="referee_discount_percent",
            field=models.PositiveSmallIntegerField(
                default=20,
                help_text="Discount percentage for referee at checkout (e.g., 20 = 20% off)",
            ),
        ),
    ]
