# Generated by Django 5.0.14 on 2026-03-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_05b4bc_idx",
            old_name="notificatio_user_id_7c0f9d_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_427e4b_idx",
            old_name="notificatio_user_id_is_read_7c0f9d_idx",
        ),
    ]
