# Generated by Django 4.2 on 2026-03-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add is_urgent field and update notification_type choices.
    Depends on existing 0002 migration.
    """

    dependencies = [
        ('notifications', '0002_rename_notificatio_user_id_7c0f9d_idx_notificatio_user_id_05b4bc_idx_and_more'),
    ]

    operations = [
        # Add is_urgent field
        migrations.AddField(
            model_name='notification',
            name='is_urgent',
            field=models.BooleanField(
                default=False,
                help_text='Urgent notifications persist until underlying issue is resolved'
            ),
        ),

        # Update notification_type field with new choices
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('system', 'System'),
                    ('content', 'Content'),
                    ('mention', 'Mention'),
                    ('telegram', 'Telegram'),
                    ('grace_period', 'Grace Period'),
                    ('expiration_warning', 'Expiration Warning'),
                    ('plan_upgraded', 'Plan Upgraded'),
                    ('gift_received', 'Gift Received'),
                    ('platform_connected', 'Platform Connected'),
                    ('downgrade_scheduled', 'Downgrade Scheduled'),
                ],
                default='system',
                max_length=30,
            ),
        ),

        # Update title field to max 100 chars per requirements
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),

        # Add composite index for efficient filtering
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['notification_type', 'is_read'],
                name='notif_type_read_idx'
            ),
        ),

        # Add composite index for user + type + read status
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(
                fields=['user', 'notification_type', 'is_read'],
                name='notif_user_type_read_idx'
            ),
        ),
    ]
