# Generated by Django 6.0.3 on 2026-03-19 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_badge_counter"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_notific_09a8d2_idx",
            old_name="notif_type_read_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="notificatio_user_id_ec6f97_idx",
            old_name="notif_user_type_read_idx",
        ),
    ]
