# Generated by Django 5.2 on 2026-03-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add SUBSCRIPTION_EXPIRED notification type.
    """

    dependencies = [
        ('notifications', '0003_notification_badge_counter'),
    ]

    operations = [
        # Update notification_type field to include SUBSCRIPTION_EXPIRED
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('system', 'System'),
                    ('content', 'Content'),
                    ('mention', 'Mention'),
                    ('telegram', 'Telegram'),
                    ('grace_period', 'Grace Period'),
                    ('expiration_warning', 'Expiration Warning'),
                    ('subscription_expired', 'Subscription Expired'),
                    ('plan_upgraded', 'Plan Upgraded'),
                    ('gift_received', 'Gift Received'),
                    ('platform_connected', 'Platform Connected'),
                    ('downgrade_scheduled', 'Downgrade Scheduled'),
                ],
                default='system',
                max_length=30,
            ),
        ),
    ]
