# Generated by Django 5.2.12 on 2026-03-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_add_expired_type"),
        (
            "notifications",
            "0004_rename_notif_type_read_idx_notificatio_notific_09a8d2_idx_and_more",
        ),
    ]

    operations = []
